### ISSUE TITLE
Tracking leagues

### ISSUE THREAD

**Issue by Daerdemandt** [odota/yasp#1187]
I haven't found a way to track leagues - so if there's some event going on, one could simply specify its league_id and all matches would be fetched automatically.

Does anyone else need this?

**Comment by howardchung** [comment]
GetMatchHistory supports a league_id parameter: https://wiki.teamfortress.com/wiki/WebAPI/GetMatchHistory

**Comment by howardchung** [comment]
Not sure if you needed more--reopen if so

**Comment by Daerdemandt** [comment]
I knew about getting matches by league_id from steam api - that's how it works now. I wanted to check if anyone else needed this functionality in yasp, but it seems that nobody does so. Thus, the issue is closed indeed.
