### ISSUE TITLE
MMR Glitch

### ISSUE THREAD

**Issue by leovarmak** [odota/yasp#1193]
Hey !

Howard this is a continuation for last closed issue. I am putting up few profiles where their MMR is displayed on Yasp but not on their in-game profile

1. [Dhruva](https://yasp.co/players/145853377)

Solo MMR on Yasp - 2185
Solo MMR on  in-game profile - Not Displayed

Will put up others later after I get home :) . 
#1170

**Comment by leovarmak** [comment]
#1170

**Comment by WTFKr0** [comment]
Hi

You can view here [https://yasp.co/players/145853377/rating]
that his mmr was catch on Nov 26 2015
That person had certainly show his mmr on that date, and next hide it 
Yasp retain the last known mmr displayed

**Comment by leovarmak** [comment]
Oh. Nice, I didn't think about this. Thanks !
