### ISSUE TITLE
SSL error on OpenDota

### ISSUE THREAD

**Issue by leovarmak** [odota/yasp#1194]
Hey !

I really like the name. Resembles the power of open source and dota combined. So on the new domain https://www.opendota.com , mixed content is being served so SSL hasn't been fully functional (atleast not green for non-nerds like me) .

Between why not .ORG TLD ? I personally think ORG is better because we are open source, not monitized and I have a few things in mind

**Comment by howardchung** [comment]
On the home page, it looks like this is due to the Sign in through Steam button not being served via https

**Comment by howardchung** [comment]
whoops tagged the wrong issue but fixed:
https://github.com/odota/yasp/commit/875370ef064549677afbaf7433d079d458128858

let me know if you find any more http references

**Comment by howardchung** [comment]
Regarding .org, I agree that it is more accurate, but .com is the "default" domain for users who can't remember the TLD and has greater recognizability.  I guess we could get both and then redirect .com to .org, but not sure if it's worth the additional expense/setup.

**Comment by leovarmak** [comment]
@howardchung I really appreciate the thing you people are doing. The sad part is that I can't donate because of my cards restrictions. So I would like to help you people by purchasing the .org domain and paying for it, mostly lifetime. What do you say ?

**Comment by howardchung** [comment]
Thanks, but I don't think that will be necessary.  It's easiest for us to manage the domains so if we need to change the DNS/routing we can do it quickly.

**Comment by leovarmak** [comment]
@howardchung do you have some email where I can write to you ?

**Comment by howardchung** [comment]
Check on my github page

**Comment by leovarmak** [comment]
:+1:  :p
