### ISSUE TITLE
Cheese x 0?

### ISSUE THREAD

**Issue by TrentBartlem** [odota/yasp#1197]
There is a new Cheese icon under a player's name on their player page.

It's zero for me, but I have donated (not recently). Does it reset each month, year, or what?

**Comment by howardchung** [comment]
It should not reset.  Did you donate anonymously?

The only change I made was making it always visible.  It used to only show up if the cheese value was non-zero.

**Comment by TrentBartlem** [comment]
Not 100% certain, but I am fairly sure I donated while logged in, to get guaranteed parsing without time limits.

I donated a dollar just now, Cheese = 1, so it's at least working for new donations.

**Comment by howardchung** [comment]
Were you untracking-immune before?  Or couldn't tell due to being a regular visitor?

**Comment by howardchung** [comment]
Anonymous donation seems to be the most likely reason for this.
