### ISSUE TITLE
name change

### ISSUE THREAD

**Issue by howardchung** [odota/yasp#585]
TODO:
- [x] rename twitter
- [x] rename discord
- [x] set ROOT_URL=https://www.opendota.com
- [x] new logo (twitter, logo.svg, favicon, discord, github)
- [x] enable cloudflare page rule to redirect old traffic
- [x] blog post/banner
- [x] redeploy

**Comment by Turmfalke2** [comment]
How is yasp a poor name? I mean it follows a fairly standard naming scheme. I never heard someone complain that yahoo is a poor name.

**Comment by albertcui** [comment]
We've seen a lot of posts on /r/dota2 complaining about the name. I don't
know if it's worth addressing though...

**Comment by howardchung** [comment]
People seem to think it should have "dota" in it

**Comment by howardchung** [comment]
Computer science guys find recursive acronyms absolutely hilarious, but the lay-Dota 2 player probably doesn't think so :(

**Comment by enche** [comment]
- Yet Another DotA Parser
- Defense of the parser

This is difficult!

-- 
adam wirth

**Comment by howardchung** [comment]
Oh and any potential name changes would need to have a decent domain available to go with it.

**Comment by Iparke** [comment]
League of Legends has the following (don't ask me how I know, I just do):
LOLKing
LOLNexus
quickfind.kassad.in (kassadin is a LoL champion)

Following the same naming conventions:
DotaKing
DotaNexus
dotabu.ff

The last one is a joke. Actually, all of it's a joke.

**Comment by howardchung** [comment]
DotaAncient?
DotaThrone

**Comment by Iparke** [comment]
Not bad. Personally, I don't know what's wrong with YASP. Unless we find something smooth with 'Dota' I prefer 'YASP' over something forced like "DotaBountyHunterTrack." I don't see why 'Dota' has to be in the name.

DotaTrack?
BountyTrack?
DotaSentry?
DotaEyes?
TreantEyes?

www.tra.ck
www.wa.rd
www.sent.ry

I am not very good at this.

**Comment by Aehrraid** [comment]
dotastats.gg

**Comment by howardchung** [comment]
lol there's already a site called dotagem and truesight is too similar to dotabuff's TrueSight service :)

**Comment by Aehrraid** [comment]
Didn't search for everyone, but your concerns about truesight are correct indeed ;)

**Comment by howardchung** [comment]
I don't think we're going to do this so I'm closing it but the list of things to do if we choose to do so could be useful :)

**Comment by Turmfalke2** [comment]
Why?

**Comment by howardchung** [comment]
To emphasize the open source nature of the project and make its association with dota more clear.  I think we will keep yasp as the name of the backend repository.
